In [1]:
# Ячейка № 1

import numpy as np
# программный инструмент
# для генерации магической матрицы
# выбранного размера


def oddOrderMagicSquare(n):
    p = np.linspace(1, n, n, dtype=int)
    M = n * ((p[..., None] + p - (n + 3) // 2) % n) + (p[..., None] + 2 * p - 2) % n + 1
    return M


def magic(n):
    if n % 2 == 1:
        M = oddOrderMagicSquare(n)

    elif n % 4 == 0:
        J = np.fix((np.linspace(1, n, n, dtype=int) % 4) / 2)
        K = J[..., None] == J
        tmp = np.arange(1, n * n + 1, n, dtype=int)
        M = tmp[..., None] + np.linspace(0, n - 1, n, dtype=int)
        M[K] = n * n + 1 - M[K]

    else:
        p = n // 2
        M = oddOrderMagicSquare(p)
        M1 = np.stack((M, M + 2 * p * p), axis=1).reshape(p, n)
        M2 = np.stack((M + 3 * p * p, M + p * p), axis=1).reshape(p, n)
        M = np.stack([M1, M2]).reshape(n, n)
        if n == 2:
            return M
        i = np.linspace(1, p, p, dtype=int)
        i = i[..., None]
        k = (n - 2) // 4
        j = np.concatenate(
            (np.linspace(1, k, k, dtype=int), np.arange(n - k + 2, n + 1, 1, dtype=int))
        )
        M[i - 1, j - 1], M[i + p - 1, j - 1] = M[i + p - 1, j - 1], M[i - 1, j - 1]
        i = k + 1
        j = np.array((1, i), dtype=int)
        M[i - 1, j - 1], M[i + p - 1, j - 1] = M[i + p - 1, j - 1], M[i - 1, j - 1]

    return M


In [2]:
# Ячейка # 2

# задаем число строк и столбцов матрицы
N = 18
# вычисляем элементы магической матрицы
Mm = magic(N)

# распечатываем целочисленную матрицу х
print(Mm)

# вычисляем суммы по столбцам, строкам и диагоналям
# сгенерированной матрицы
s1 = 0
s2 = 0
Qq = np.zeros(N)
Qp = np.zeros(N)

for i in range(N):
    Qq[i] = np.sum(Mm[i, :])
    Qp[i] = np.sum(Mm[:, i])

for i in range(N):
    s1 = s1 + Mm[i, i]
    s2 = s2 + Mm[N - i - 1, N - i - 1]
# проверяем, что сгенерированная матрица
# явялется магической матрицей
Test = 0
if s1 == s2:
    for i in range(N):
        if ~(s1 == s2 == Qq[i] == Qp[i]):
            Test = 1
if Test == 0:
    print(
        "\n Матрица магическая \n\n",
        "Суммы по столбцам, строкам и диагоналям равняются",
        int(s1),
    )
else:
    print("Матрица не является магической")

[[290 301 312 323   1  12  23  34  45 209 220 231 242 163 174 104 115 126]
 [300 311 322 252  11  22  33  44  46 219 230 241 171 173 184 114 125 127]
 [310 321 251 253  21  32  43  54  56 229 240 170 172 183 194 124 135 137]
 [320 250 261 263  31  42  53  55  66 239 169 180 182 193 204 134 136 147]
 [  6 260 262 273 284  52  63  65  76 168 179 181 192 203 214 144 146 157]
 [259 270 272 283  51  62  64  75   5 178 189 191 202 213 224 145 156  86]
 [269 271 282 293  61  72  74   4  15 188 190 201 212 223 234 155  85  96]
 [279 281 292 303  71  73   3  14  25 198 200 211 222 233 235  84  95 106]
 [280 291 302 313  81   2  13  24  35 199 210 221 232 243 164  94 105 116]
 [ 47  58  69  80 244 255 266 277 288 128 139 150 161  82  93 185 196 207]
 [ 57  68  79   9 254 265 276 287 289 138 149 160  90  92 103 195 206 208]
 [ 67  78   8  10 264 275 286 297 299 148 159  89  91 102 113 205 216 218]
 [ 77   7  18  20 274 285 296 298 309 158  88  99 101 112 123 215 217 228]
 [249  17  19  30  41 295